[project]
name = "tropical_time"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Jinja2~=3.1.2",
    "pillow~=11.0.0",
    "pyyaml~=6.0.2",
    "rich~=12.5.1",
    "numpy~=2.2.3",
    "unidecode",
    "tqdm",
    "wcag_contrast_ratio"
]